# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/ip/iram/iram.xci
# IP: The module: 'iram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/ip/iram/iram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/ip/iram/iram.xci
# IP: The module: 'iram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/ip/iram/iram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
