######################################################################
#
# File name : sccomp_dataflow_wave.do
# Created on: Sun Jun 17 00:44:44 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
