######################################################################
#
# File name : sccomp_dataflow_compile.do
# Created on: Sun Jun 17 00:44:30 +0800 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech_pe_10.4c\\win32pe\\vlib work
D:\\modeltech_pe_10.4c\\win32pe\\vlib msim

D:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib
D:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xpm
D:\\modeltech_pe_10.4c\\win32pe\\vlib msim/dist_mem_gen_v8_0_10

D:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib
D:\\modeltech_pe_10.4c\\win32pe\\vmap xpm msim/xpm
D:\\modeltech_pe_10.4c\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10

D:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../CPU54_down.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"D:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \

D:\\modeltech_pe_10.4c\\win32pe\\vcom -64 -93 -work xpm  \
"D:/Xilinx/Vivado/2016.2/data/ip/xpm/xpm_VCOMP.vhd" \

D:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../CPU54_down.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../CPU54_down.srcs/sources_1/new/DIVU.v" \
"../../../CPU54_down.srcs/sources_1/new/xor_c.v" \
"../../../CPU54_down.srcs/sources_1/new/slt_c.v" \
"../../../CPU54_down.srcs/sources_1/new/nor_c.v" \
"../../../CPU54_down.srcs/sources_1/new/lui_c.v" \
"../../../CPU54_down.srcs/sources_1/new/instruction_decoder.v" \
"../../../CPU54_down.srcs/sources_1/new/bshifter_32carry.v" \
"../../../CPU54_down.srcs/sources_1/new/and_c.v" \
"../../../CPU54_down.srcs/sources_1/new/addsub32.v" \
"../../../CPU54_down.srcs/sources_1/new/or_c.v" \
"../../../CPU54_down.srcs/sources_1/new/DIV.v" \
"../../../CPU54_down.srcs/sources_1/new/selector.v" \
"../../../CPU54_down.srcs/sources_1/new/regfiles.v" \
"../../../CPU54_down.srcs/sources_1/new/pcreg.v" \
"../../../CPU54_down.srcs/sources_1/new/HILOreg.v" \
"../../../CPU54_down.srcs/sources_1/new/ext.v" \
"../../../CPU54_down.srcs/sources_1/new/divmul.v" \
"../../../CPU54_down.srcs/sources_1/new/cp0.v" \
"../../../CPU54_down.srcs/sources_1/new/countZero.v" \
"../../../CPU54_down.srcs/sources_1/new/control_unit_54.v" \
"../../../CPU54_down.srcs/sources_1/new/alu.v" \
"../../../CPU54_down.srcs/sources_1/new/add2.v" \

D:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  "+incdir+../../../CPU54_down.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../CPU54_down.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

D:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../CPU54_down.ip_user_files/ipstatic/clk_wiz_v5_3_1" \
"../../../CPU54_down.srcs/sources_1/ip/iram/sim/iram.v" \
"../../../CPU54_down.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../CPU54_down.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../CPU54_down.srcs/sources_1/new/dram.v" \
"../../../CPU54_down.srcs/sources_1/new/cpu54.v" \
"../../../CPU54_down.srcs/sources_1/new/io_sel.v" \
"../../../CPU54_down.srcs/sources_1/new/seg7x16.v" \
"../../../CPU54_down.srcs/sources_1/new/sw_mem_sel.v" \
"../../../CPU54_down.srcs/sources_1/new/sccomp_dataflow.v" \

# compile glbl module
D:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

