# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath D:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vivado_projects/CPU54_down/CPU54_down.cache/wt [current_project]
set_property parent.project_path E:/vivado_projects/CPU54_down/CPU54_down.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files c:/Users/lenovo/Desktop/mips_54_mars_switch_student.coe
add_files c:/Users/lenovo/Desktop/mips_54_mars_board_switch_student.coe
add_files -quiet e:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files e:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet e:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/ip/iram/iram.dcp
set_property used_in_implementation false [get_files e:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/ip/iram/iram.dcp]
read_verilog -library xil_defaultlib {
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/DIVU.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/xor_c.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/slt_c.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/nor_c.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/lui_c.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/instruction_decoder.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/bshifter_32carry.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/and_c.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/addsub32.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/or_c.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/DIV.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/selector.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/regfiles.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/pcreg.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/HILOreg.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/ext.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/divmul.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/cp0.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/countZero.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/control_unit_54.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/alu.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/add2.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/dram.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/cpu54.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/io_sel.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/seg7x16.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/sw_mem_sel.v
  E:/vivado_projects/CPU54_down/CPU54_down.srcs/sources_1/new/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/vivado_projects/CPU54_down/CPU54_down.srcs/constrs_1/new/cpu.xdc
set_property used_in_implementation false [get_files E:/vivado_projects/CPU54_down/CPU54_down.srcs/constrs_1/new/cpu.xdc]


synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
